[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
<<<<<<< HEAD
authors = ["Oleg"]
=======
authors = ["Oleg <ustas201354@gmail.com>"]
>>>>>>> 6018afa3550fce94838c58d9cc74745d779221fc
packages = [
  { include = "brain_games" },
]

<<<<<<< HEAD
[tool.poetry.dependencies]
python = "^3.9"
=======

[tool.poetry.dependencies]
python = "^3.8"
<<<<<<< HEAD
>>>>>>> 6018afa3550fce94838c58d9cc74745d779221fc
=======
prompt = "^0.4.1"
>>>>>>> c7e8be6b6824cc74f5c0790eb979ce25bb8aae3c

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"
