name: install_python
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: setup_python
        uses: actions/checkout@v2
        uses: actions/setup-python@v2
            with:
              python-version: '3.x'
