name: install_python
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: setup_python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
